spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${kc.host}/realms/${kc.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs



